// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9x3Y8hx7BICTiWGrVDDwHLMj3PK8r79w',
    appId: '1:272939696187:web:1ced00aafa50f75b879c1e',
    messagingSenderId: '272939696187',
    projectId: 'note-mobile-v2-firebase',
    authDomain: 'note-mobile-v2-firebase.firebaseapp.com',
    storageBucket: 'note-mobile-v2-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Pfiu2MNdjp9ujfczi7-nfPAfyP1mUHE',
    appId: '1:272939696187:android:8c3a59b75e7cd3e2879c1e',
    messagingSenderId: '272939696187',
    projectId: 'note-mobile-v2-firebase',
    storageBucket: 'note-mobile-v2-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB34TV6lPrYY7F4Kb634SdYHrjZ5XCUEzY',
    appId: '1:272939696187:ios:f515f3896ff0953a879c1e',
    messagingSenderId: '272939696187',
    projectId: 'note-mobile-v2-firebase',
    storageBucket: 'note-mobile-v2-firebase.appspot.com',
    iosClientId: '272939696187-piaio7fahq61er7nvacl9l2pkskn3jup.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteMobileV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB34TV6lPrYY7F4Kb634SdYHrjZ5XCUEzY',
    appId: '1:272939696187:ios:f515f3896ff0953a879c1e',
    messagingSenderId: '272939696187',
    projectId: 'note-mobile-v2-firebase',
    storageBucket: 'note-mobile-v2-firebase.appspot.com',
    iosClientId: '272939696187-piaio7fahq61er7nvacl9l2pkskn3jup.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteMobileV2',
  );
}
